name: Game data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "5 4 15 * *" # Run at 04:05 on day-of-month 15.

jobs:
  data_workflow:
    name: Data workflow
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: "1.25"
          cache-dependency-path: app/go.sum

      # Caching go modules to speed up the run
      - uses: actions/cache@v4.3.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: awesome-software-engineering-games Convert YAML to JSON
        run: ./awesome-software-engineering-games convertYamlToJson --yaml-directory ../games --json-directory ../generated

      - name: awesome-software-engineering-games Gather additional game data
        run: ./awesome-software-engineering-games collectGameData --json-directory ../generated

      - name: awesome-software-engineering-games Convert JSON to README
        run: ./awesome-software-engineering-games convertJsonToReadme --json-directory ../generated --readme-template ../assets/README.template --readme-output ../README.md

      # Commit results back to repository
      - uses: stefanzweifel/git-auto-commit-action@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated game content
          branch: main
          commit_user_name: Game data update bot
          commit_user_email: stehtisch@engineeringkiosk.dev
          commit_author: Game data update bot <stehtisch@engineeringkiosk.dev>

      - name: Trigger webpage to sync
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
          repository: EngineeringKiosk/webpage
          event-type: game-list-update
